name: Deploy to Azure Function

# Run whenever a release is created through github
# on:
#   release:
#     types: ["created"]

# Run when the Run Tests workflow completes.
# We will also check if the workflow completed on the main branch and only if it on a tag.
on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

env:
  AZURE_FUNCTIONAPP_NAME: "ischtn-hello-action"
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
  PYTHON_VERSION: "3.9.2"

jobs:
  test-everything:
    runs-on: ubuntu-latest

  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Tag was pushed to main."

      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: "Build with pipenv"
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install pipenv --upgrade pip
          pipenv lock -r | sed 's/-e //g' | pip install --upgrade -r /dev/stdin --target=".python_packages/lib/site-packages"
          pipenv graph
          popd

      - name: "Deploy to azure"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
