name: Run Tests

# Run on push or merge of PR on any branch that's not a feature branch.
on:
  push:
    tags: releases/[0-9]+.[0-9]+.[0-9]+
    branches: ["main", "develop"]

env:
  AZURE_FUNCTIONAPP_NAME: "ischtn-hello-action"
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
  PYTHON_VERSION: "3.9"

jobs:
  test-all:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: "Build with pipenv"
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install pipenv --upgrade pip
          pipenv install --dev
          popd

      - name: "Check test"
        shell: bash
        run: |
          pipenv run pytest

      - name: "Check for linter errors"
        shell: bash
        run: |
          pipenv run flake8 ./**/*.py -v

  deploy:
    needs: test-all
    if: startsWith( github.ref, 'refs/tags/releases/')
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: "Build for deployment"
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          cat Pipfile.lock | sed 's/-e //g' | pip install --upgrade -r /dev/stdin --target=".python_packages/lib/site-packages"
          popd

      - name: "Deploy to azure"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
