name: Run Tests

# Run on push or merge of PR on any branch.
on: push

env:
  AZURE_FUNCTIONAPP_NAME: "ischtn-hello-action"
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
  PYTHON_VERSION: "3.9"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: "Build with pipenv"
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install pipenv --upgrade pip
          pipenv install --dev
          popd

      - name: "Test"
        shell: bash
        run: |
          pipenv run pytest

      - name: "Check with Linter"
        shell: bash
        run: |
          pipenv run flake8 ./**/*.py -v
